### ISSUE TITLE
he request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by HaiyanDu7** [AuthorizeNet/sample-code-csharp#94] opened 2019-01-17 20:43 UTC
when I run "CreateAnAcceptPaymentTransaction"
I got this error
System.Net.WebException: 'The request was aborted: Could not create SSL/TLS secure channel.'

**Comment by cforbesywam** [comment] 2019-01-30 23:09
I have the same issue when I attempted a test ChargeCreditCard transactions against the Sandbox

**Comment by cforbesywam** [comment] 2019-02-05 20:47
I believe this issue is related to an issue with the sdk-dotnet library see: https://github.com/AuthorizeNet/sdk-dotnet/issues/234 
Since the SampleCode  program exits on the first exception I can not confirm if subsequent attempts would connect correctly but running the unit test on the sdk-dotnet library has confirmed this to be an issue.  If it re-order the unit tests I see any test after the first connection attempt will pass but the first connection attempt will consistently fail.  Since the sample code is using the sdk-donnet library and fails on the first attempt it is very likely to be the same issue.

**Comment by cforbesywam** [comment] 2019-02-06 23:49
I believe I may have a fix for this issue ….
See Issue: https://github.com/AuthorizeNet/sdk-dotnet/issues/234
See Pull request: https://github.com/AuthorizeNet/sdk-dotnet/pull/249

**Comment by gnongsie** [comment] 2019-03-06 09:51
Hi,

The latest version of the SDK has merged a fix for this issue (Thanks @cforbesywam).

Kindly test with the latest SDK and let us know if the issue still persists.

**Comment by cforbesywam** [comment] 2019-03-06 15:52
Hello Gabriel,

I’ve updated the AuthorizeNet package and all my unit tests are now passing which was NOT happening on before this edition.  So I can confirm this has fixed the issue!

Thank you for releasing this fix.

Blessings,


Colin Forbes
Research & Information
Part of the YWAM global family of ministries

**Comment by gnongsie** [comment] 2019-03-13 05:06
Thank you for the testing.

I'll be closing this issue. Feel free to raise a new issue if any problems arise.

**Closed as completed by gnongsie** 2019-03-13 05:06 UTC
Labels: awaiting-reply
